kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: ubuntu:focal
  commands:
  - scripts/travis/apt-install make gcc pkg-config git perl-modules
  - make -C scripts/travis local
