language: c
dist: focal
compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VIgGghpeqqcFL1/Y555Ka4In/cvat3K4u8vcICV37e0Qx8qLC5AZZXjaK5gyaFen320QVur0Cyl/6/a/EcwF8NFoeTZyE2g2hUQu6EpafXnhSYcsTHTS4c1G5U6uvOt5mZfEX1mwJQ8os8Kc8yGmU5hSDm6UiJHNDrAXSVgBnoaHMffC2PJgwfGi9j45SYA4AI3OPKxy3GXkgsW2OjWSguQpK7wI8C9QwFUTuizq0VmMyE3YVTjvhnht8gdIPu/C4guEEkvj8SpsyigdMoPMU7aJ5FVRnoboWrQBG1MWaZjCngSVDcQ90En3a0n0SekxRmaum2y9Pi7PAdFlNUz3Bx1a5cvi9VNnKCu2JR59pLrnkXBszzPIba3yPZc7GchcG5MkF/WjhjcTJSNwOW69qNr5K5Ja/bnMds2Gw5EjBeenpePcMvzyINimYG0ACI3ZjmRoDKfubzy2bkdauXX7i23yST4KsL0/TInHuOT3w6WbV515gSS7R1UBFR01tWQfD5lgQi3iI7gfaqpWMrOXyDm9xZJjKbG67r7oVxsbaGejeRWGj4k4xNdTVh5q+vXJRIKnpbssXFODcts5JXu3DeKKBoWiSnn/qhcy6sqVDARcVzUz6eRBL9uS2GwYKFDTG+E6z6nyAI2xd9TLiLbXWUcFpSlYH4tLpN21l6gk3iA="

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq protobuf-c-compiler libprotobuf-c-dev libaio-dev libprotobuf-dev protobuf-compiler libcap-dev libnl-3-dev gcc-multilib libc6-dev-i386 libnet-dev libnl-route-3-dev libgnutls28-dev libgnutls30 libnftables-dev bsdmainutils build-essential iptables libselinux-dev pkg-config
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "adrianreber/criu"
      description: "<Your project description here>"
    notification_email: areber@redhat.com
    build_command_prepend: true
    build_command: make -j 8
    branch_pattern: coverity

script:
  - make -j 8
