language: c
os: linux
dist: bionic
cache: ccache
services:
  - docker
jobs:
  include:
    - os: linux
      arch: ppc64le
      env: TR_ARCH=local
      dist: bionic
    - os: linux
      arch: ppc64le
      env: TR_ARCH=local CLANG=1
      dist: bionic
    - os: linux
      arch: s390x
      env: TR_ARCH=local
      dist: bionic
    - os: linux
      arch: arm64
      env: TR_ARCH=local
      dist: bionic
    - os: linux
      arch: arm64
      env: TR_ARCH=local CLANG=1
      dist: bionic
    - os: linux
      arch: arm64
      # This runs on aarch64 with 'setarch linux32'
      env: TR_ARCH=armv7hf
      dist: bionic
    - os: linux
      arch: arm64
      # This runs on aarch64 with 'setarch linux32'
      env: TR_ARCH=armv7hf     CLANG=1
      dist: bionic
script:
  - sudo make CCACHE=1 -C scripts/travis $TR_ARCH
after_success:
  - ccache -s
  - make -C scripts/travis after_success
