name: Alpine Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [GCC=1, CLANG=1]

    steps:
    - uses: actions/checkout@v2
    - name: Run Alpine ${{ matrix.target }} Test
      shell: 'script -q -e -c "bash {0}"'
      run: sudo -E make -C scripts/ci alpine ${{ matrix.target }}
