name: Tainted

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: sudo -E make -C scripts/ci/ centos8
    - name: Check tainted
      run: cat /proc/sys/kernel/tainted
